#!/usr/bin/env bash
set -euo pipefail

# Apply a low-risk runtime slim profile without patching upstream core files.
# This script only generates env/compose overlay files and can optionally restart services.

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_ENV="${HOME}/.nanobot/runtime-slim.env"
OUT_COMPOSE="${REPO_DIR}/docker-compose.slim.yml"
GATEWAY_MEM="600m"
API_MEM="512m"
GATEWAY_CPU="1.0"
API_CPU="0.8"
APPLY=false

usage() {
  cat <<'USAGE'
Usage:
  scripts/apply_slim_profile.sh [options]

Options:
  --env-file <path>       Runtime env output (KEY=VALUE). Default: ~/.nanobot/runtime-slim.env
  --compose-file <path>   Compose override output. Default: ./docker-compose.slim.yml
  --gateway-mem <value>   Gateway memory limit. Default: 600m
  --api-mem <value>       API memory limit. Default: 512m
  --gateway-cpu <value>   Gateway cpu limit. Default: 1.0
  --api-cpu <value>       API cpu limit. Default: 0.8
  --apply                 Apply now with docker compose up -d
  -h, --help              Show this help

Examples:
  scripts/apply_slim_profile.sh
  scripts/apply_slim_profile.sh --gateway-mem 512m --api-mem 384m --apply
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env-file) OUT_ENV="${2:-}"; shift 2 ;;
    --compose-file) OUT_COMPOSE="${2:-}"; shift 2 ;;
    --gateway-mem) GATEWAY_MEM="${2:-}"; shift 2 ;;
    --api-mem) API_MEM="${2:-}"; shift 2 ;;
    --gateway-cpu) GATEWAY_CPU="${2:-}"; shift 2 ;;
    --api-cpu) API_CPU="${2:-}"; shift 2 ;;
    --apply) APPLY=true; shift 1 ;;
    -h|--help) usage; exit 0 ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 2 ;;
  esac
done

mkdir -p "$(dirname "$OUT_ENV")"
mkdir -p "$(dirname "$OUT_COMPOSE")"

cat > "$OUT_ENV" <<EOF
# Generated by scripts/apply_slim_profile.sh
PYTHONUNBUFFERED=1
PYTHONDONTWRITEBYTECODE=1
PYTHONMALLOC=malloc
MALLOC_ARENA_MAX=2
MALLOC_TRIM_THRESHOLD_=131072
EOF

cat > "$OUT_COMPOSE" <<EOF
services:
  nanobot-gateway:
    env_file:
      - ${OUT_ENV}
    deploy:
      resources:
        limits:
          cpus: "${GATEWAY_CPU}"
          memory: ${GATEWAY_MEM}
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"

  nanobot-api:
    env_file:
      - ${OUT_ENV}
    deploy:
      resources:
        limits:
          cpus: "${API_CPU}"
          memory: ${API_MEM}
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"
EOF

echo "[slim] wrote env: $OUT_ENV"
echo "[slim] wrote compose override: $OUT_COMPOSE"
echo "[slim] start with: docker compose -f docker-compose.yml -f $(basename "$OUT_COMPOSE") up -d nanobot-gateway"

if $APPLY; then
  cd "$REPO_DIR"
  services="nanobot-gateway"
  if docker compose config --services | grep -qx "nanobot-api"; then
    services="nanobot-gateway nanobot-api"
  fi
  echo "[slim] applying profile to: $services"
  docker compose -f docker-compose.yml -f "$OUT_COMPOSE" up -d $services
  echo "[slim] applied"
fi