#!/usr/bin/env bash
set -euo pipefail

# Apply Reflexio runtime glue without modifying nanobot core.
# Generates shell env + compose env + compose override for gateway/api.

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REFLEXIO_URL="http://127.0.0.1:8081"
MODULE_NAME="extensions.reflexio"
OUT_SHELL_ENV="${HOME}/.nanobot/reflexio.env"
OUT_COMPOSE_ENV="${HOME}/.nanobot/reflexio.compose.env"
OUT_COMPOSE="${REPO_DIR}/docker-compose.reflexio.yml"
APPLY=false

usage() {
  cat <<'USAGE'
Usage:
  scripts/apply_reflexio_glue.sh [options]

Options:
  --url <value>           Reflexio base URL. Default: http://127.0.0.1:8081
  --module <value>        Extension module name. Default: extensions.reflexio
  --shell-env <path>      Shell env output (export format). Default: ~/.nanobot/reflexio.env
  --compose-env <path>    Compose env output (KEY=VALUE). Default: ~/.nanobot/reflexio.compose.env
  --compose-file <path>   Compose override output. Default: ./docker-compose.reflexio.yml
  --apply                 Apply now with docker compose up -d
  -h, --help              Show this help

Examples:
  scripts/apply_reflexio_glue.sh --url http://127.0.0.1:8081
  scripts/apply_reflexio_glue.sh --module extensions.reflexio --apply
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --url) REFLEXIO_URL="${2:-}"; shift 2 ;;
    --module) MODULE_NAME="${2:-}"; shift 2 ;;
    --shell-env) OUT_SHELL_ENV="${2:-}"; shift 2 ;;
    --compose-env) OUT_COMPOSE_ENV="${2:-}"; shift 2 ;;
    --compose-file) OUT_COMPOSE="${2:-}"; shift 2 ;;
    --apply) APPLY=true; shift 1 ;;
    -h|--help) usage; exit 0 ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 2 ;;
  esac
done

mkdir -p "$(dirname "$OUT_SHELL_ENV")"
mkdir -p "$(dirname "$OUT_COMPOSE_ENV")"
mkdir -p "$(dirname "$OUT_COMPOSE")"

health_code="$(curl -s -o /dev/null -w '%{http_code}' "${REFLEXIO_URL}/health" || true)"
if [[ "$health_code" != "200" ]]; then
  echo "Error: reflexio health check failed: ${REFLEXIO_URL}/health (code=${health_code})" >&2
  exit 1
fi

cat > "$OUT_SHELL_ENV" <<EOF
# Generated by scripts/apply_reflexio_glue.sh
export NANOBOT_REFLEXIO_URL="${REFLEXIO_URL}"
export NANOBOT_REFLEXIO_PUBLISH_URL="${REFLEXIO_URL}/api/publish_interaction"
export NANOBOT_REFLEXIO_SEARCH_URL="${REFLEXIO_URL}/api/search"
export NANOBOT_EXTENSION_MODULES="${MODULE_NAME}"
EOF

cat > "$OUT_COMPOSE_ENV" <<EOF
# Generated by scripts/apply_reflexio_glue.sh
NANOBOT_REFLEXIO_URL=${REFLEXIO_URL}
NANOBOT_REFLEXIO_PUBLISH_URL=${REFLEXIO_URL}/api/publish_interaction
NANOBOT_REFLEXIO_SEARCH_URL=${REFLEXIO_URL}/api/search
NANOBOT_EXTENSION_MODULES=${MODULE_NAME}
EOF

cat > "$OUT_COMPOSE" <<EOF
services:
  nanobot-gateway:
    env_file:
      - ${OUT_COMPOSE_ENV}

  nanobot-api:
    env_file:
      - ${OUT_COMPOSE_ENV}
EOF

echo "[reflexio] health check ok: ${REFLEXIO_URL}"
echo "[reflexio] wrote shell env: $OUT_SHELL_ENV"
echo "[reflexio] wrote compose env: $OUT_COMPOSE_ENV"
echo "[reflexio] wrote compose override: $OUT_COMPOSE"
echo "[reflexio] shell usage: source $OUT_SHELL_ENV"
echo "[reflexio] compose usage: docker compose -f docker-compose.yml -f $(basename "$OUT_COMPOSE") up -d nanobot-gateway"

if $APPLY; then
  cd "$REPO_DIR"
  services="nanobot-gateway"
  if docker compose config --services | grep -qx "nanobot-api"; then
    services="nanobot-gateway nanobot-api"
  fi
  echo "[reflexio] applying profile to: $services"
  docker compose -f docker-compose.yml -f "$OUT_COMPOSE" up -d $services
  echo "[reflexio] applied"
fi